### ISSUE TITLE
Feature Request: Browserify feathers-rx for angular2

### ISSUE THREAD

**Issue by netzwerch** [feathersjs/feathers-rx#3]
Hi feathers team,
I'd like to use the rx-extension also in the browser (in an angular2 application). Currently there is no possibility as it seems to me.
I already tried to use browserify in the same way as the feathers-client does, but sadly without a usable result. Does someone know how to achieve this?

**Comment by harangue** [comment]
Hey @netzwerch, feathers-rx absolutely works in the browser! You'll have to build the files from the ES6 source (download repo, `npm install`, `npm run compile`) but once you've done that you should be good to go!

Normally feathers repositories have this `/lib` folder committed and ready to go, but since feathers-rx is still highly experimental we're waiting for an initial release to do that and list it on npm. Expect this within a week, I hope.

**Comment by netzwerch** [comment]
Thx @harangue, thats a good info. I tried but wasn't able to use it in angular2. I assume it's either because of the compilation to a CommonJS module (I currently use the angular2 quickstart that uses SystemJS), or that there is a TypeScript definition missing.
I'll keep digging into that and report what I find out.

**Comment by daffl** [comment]
I just published the first version of this module to npm as [feathers-rx](https://github.com/feathersjs/feathers-rx) and a browserified version can be found in the `dist/` folder. It currently includes RxJS (which we probably want to change for the next release) but it should be usable. The direct CDN link is: https://npmcdn.com/feathers-rx@^0.1.0/dist/feathers-rx.js
